apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/lnxlabs/kubeblocks-test.git
    targetRevision: main
    path: manifests/crds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true