apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://apecloud.github.io/helm-charts
    chart: kubeblocks
    targetRevision: 1.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
